# Generated by Django 4.0 on 2022-03-22 21:53

import base.models.item_models
import base.models.order_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=base.models.item_models.create_random_id, max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='ユーザー名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=32, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_slug', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=32, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.user')),
                ('first_name', models.CharField(blank=True, default='', max_length=20, verbose_name='ファーストネーム')),
                ('last_name', models.CharField(blank=True, default='', max_length=20, verbose_name='ラストネーム')),
                ('zipcode', models.CharField(blank=True, default='', max_length=20, verbose_name='郵便番号')),
                ('prefecture', models.CharField(blank=True, default='', max_length=50, verbose_name='都道府県')),
                ('address1', models.CharField(blank=True, default='', max_length=50, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, default='', max_length=50, verbose_name='住所2')),
                ('phone_num', models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=base.models.order_models.custom_timestamp_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('uid', models.CharField(editable=False, max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('tax_included', models.PositiveIntegerField(default=0)),
                ('items', models.JSONField()),
                ('shipping_for', models.JSONField()),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=base.models.item_models.create_random_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='値段')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='在庫')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='売上個数')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='詳細')),
                ('images', models.ImageField(blank=True, default='', upload_to=base.models.item_models.upload_image_to, verbose_name='関連画像')),
                ('is_published', models.BooleanField(default=False, verbose_name='販売状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category')),
                ('tags', models.ManyToManyField(to='base.Tag')),
            ],
        ),
    ]
